#!/usr/bin/env bash
set -e

dir="$HOME/Pictures/screenshots"
mkdir -p "$dir"

if [ -n "$WAYLAND_DISPLAY" ]; then
    types=$(wl-paste --list-types)
    if grep -q '^image/' <<<"$types"; then
        ext=$(grep -m1 '^image/' <<<"$types" | cut -d/ -f2 | cut -d';' -f1)
        file="$dir/clip_$(date +%s).${ext}"
        wl-paste > "$file"
        echo -n "$file"
    else
        wl-paste --no-newline
    fi
elif [ -n "$DISPLAY" ]; then
    types=$(xclip -selection clipboard -t TARGETS -o)
    if grep -q '^image/' <<<"$types"; then
        ext=$(grep -m1 '^image/' <<<"$types" | cut -d/ -f2 | cut -d';' -f1)
        file="$dir/clip_$(date +%s).${ext}"
        xclip -selection clipboard -t "image/${ext}" -o > "$file"
        echo -n "$file"
    else
        xclip -selection clipboard -o
    fi
fi
